steps:
  - label: "AMDGPU - Julia 1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    command: |
      apt-get update && apt-get install -y xvfb
      Xvfb :99 -screen 0 1280x1024x24 &
      export DISPLAY=:99
      julia --project -e 'using Pkg; Pkg.update()'
    timeout_in_minutes: 30
    env:
      JULIA_NUM_THREADS: 4
      GSP_TEST_AMDGPU: true

  - label: "CUDA - Julia 1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: |
      apt-get update && apt-get install -y xvfb
      Xvfb :99 -screen 0 1280x1024x24 &
      export DISPLAY=:99
      julia --project -e 'using Pkg; Pkg.update()'
    timeout_in_minutes: 30
    env:
      JULIA_NUM_THREADS: 4
      GSP_TEST_CUDA: true
